### ISSUE TITLE
Error for required packages

### ISSUE THREAD

**Issue by c4m1l0-lending** [muchzill4/kitty-session#1]
Hi! I was trying your tmux based solution for open kitty sessions but when the kitten runs throws this error
![imagen](https://user-images.githubusercontent.com/85175729/124366807-fd7b3200-dc17-11eb-8532-beab30cafd85.png)
Could you please help me with this issue?

**Comment by muchzill4** [comment]
~~Oh my. I'm sorry - I have completely missed this issue. Are you still experiencing it?~~

FWIW I'm not using this script anymore, as I went back to tmux. Now that we have excuses out of the way - I think I managed to fix the issue you're describing [here](https://github.com/muchzill4/kitty-session/commit/7ae7b4f6b3496d4f062d665b6acbcc93818875e1).
